### ISSUE TITLE
Problems with styled-components as non-peer dependency

### ISSUE THREAD

**Issue by gregoralbrecht** [jxnblk/grid-styled#88] opened 2018-02-21 09:32 UTC
I recently started using `grid-styled` in a CRA-based project with `styled-components`. In development, everything is fine, but in the production build, some pages are missing styles.

Without going into too much detail, this seems to be because `grid-styled` has `styled-components` as a dependency, although it *should* be a peer dependency. See this issue for further information: https://github.com/styled-components/styled-components/pull/1412#issuecomment-355835024

For some reason, my issue was resolved when updating `styled-components` but I think that linked issue might still be interesting for you :)

PS: Not sure if it's the same issue, but https://github.com/jxnblk/grid-styled/issues/86 seems related.

**Comment by chrishurlburt** [comment] 2018-03-13 19:17
I'm having this issue as well, I believe styled-components should be a peerDependency of grid-styled.

I'm developing a package that has grid-styled as a dependency and styled-components as a peerDependency. When I install my package into an app ALSO using styled-components, the expected behavior is that my package (as well as grid-styled) would rely on the app's copy of styled-components.

What's happening is the app effectively ends up with 2 copies of styled-components -- grid-styled's and the apps own version. In order for grid-styled to be used in an app that already has styled-components as a dependency, grid-styled must list styled-components as peerDependency and NOT bundle it with the production bundle. Otherwise, everything breaks due to duplicate copies running.

**Comment by jxnblk** [comment] 2018-04-24 14:14
Should be fixed in v4

**Closed by jxnblk** 2018-04-24 14:14 UTC
