### ISSUE TITLE
Error when loading page 

### ISSUE THREAD

**Issue by santaclauze** [jxnblk/grid-styled#2] opened 2016-11-10 05:46 UTC
Hey,

I was testing your grid-styled but I had the following issue. After using "npm i grid-styled" on my project I imported Grid as followed by the doc but I encountered the following error:

`Dynamic page loading failed TypeError: (0 , _styledComponents2.default) is not a function(…)`

So, I copy-pasted the `/src/Grid.js` by itself ni a directory that I imported straight to my testing page and that enabled the Grid to work properly. I then tried the same process but this time with `/dist/Grid.js`, This time i encountered the same error. 

It seems, but I am not sure, that there is an issue with Grid.js when it is used via its ES5 version.

**Comment by colophonemes** [comment] 2016-11-11 12:34
Yeah, having the same issue, using `grid-styled` with `react-boilerplate`. I've tried importing the `src` file directly...

```js
import Grid from 'grid-styled/src/Grid.js'
```

... but then the loader chokes on the JSX exports. 

If I try importing that file with Babel explicitly...

```js
import Grid from 'babel!grid-styled/src/Grid.js'
```

... then it throws the same `TypeError` @santaclauze was seeing

**Comment by jxnblk** [comment] 2016-11-11 15:47
I'm unable to reproduce. Would you mind sharing your `.babelrc` or any other config you have?

**Comment by santaclauze** [comment] 2016-11-14 04:57
First bear with me, I am a bit of a noob, but I will try my best to be clear:

In m project I do not have a .babelrc as main config file is a .JSON, but I believe that what ever is contained in the .babelrc is notmally in the .JSON:

`babel": {
    "presets": [
      [
        "latest",
        {
          "es2015": {
            "modules": false
          }
        }
      ],
      "react",
      "stage-0"
    ],`

As for the dependencies, I applied `--save-dev` when installing the grid. Here are my Dev dependencies related to Babel: `"babel-cli": "6.14.0",
    "babel-core": "6.14.0",
    "babel-eslint": "6.1.2",
    "babel-loader": "6.2.5",
    "babel-plugin-istanbul": "2.0.1",
    "babel-plugin-react-intl": "2.2.0",
    "babel-plugin-react-transform": "2.0.2",
    "babel-plugin-transform-react-constant-elements": "6.9.1",
    "babel-plugin-transform-react-inline-elements": "6.8.0",
    "babel-plugin-transform-react-remove-prop-types": "0.2.9",
    "babel-preset-latest": "6.14.0",
    "babel-preset-react": "6.11.1",
    "babel-preset-react-hmre": "1.1.1",
    "babel-preset-stage-0": "6.5.0",`

I tested it again this morning and the same issue persists. Do you need anything else?

**Comment by amccloud** [comment] 2016-12-06 20:45
@santaclauze are you using webpack 2? I have the same issue.

**Comment by jimmynames** [comment] 2017-01-12 14:33
Hey, imported this into a pretty much clean boilerplate of react and getting same error.. 

` 0 , _styledComponents2.default) is not a function `

``` routes.js?6db9:10 Dynamic page loading failed TypeError: (0 , _styledComponents2.default) is not a function
    at eval (eval at ./node_modules/grid-styled/dist/Grid.js (5.chunk.js:173), <anonymous>:59:43)
    at Object../node_modules/grid-styled/dist/Grid.js (5.chunk.js:173)
    at __webpack_require__ (main.js:681)
    at fn (main.js:106)
    at eval (eval at ./app/containers/HomePage/index.js (5.chunk.js:119), <anonymous>:5:70)
    at Object../app/containers/HomePage/index.js (5.chunk.js:119)
    at __webpack_require__ (main.js:681)
    at fn (main.js:106)
```

**Comment by jxnblk** [comment] 2017-06-14 02:00
Closing for now, but please let me know if this is still an issue with v2

**Closed by jxnblk** 2017-06-14 02:00 UTC
