### ISSUE TITLE
http://jxnblk.com/grid-styled/ not working on IE11

### ISSUE THREAD

**Issue by soenkekluth** [jxnblk/grid-styled#10] opened 2017-06-14 12:24 UTC
SCRIPT438: Object doesn't support property or method 'isInteger'
File: bundle.js, Line: 20, Column: 46504

**Comment by jxnblk** [comment] 2017-06-19 23:41
Not sure how to reproduce this, are you sure this isn't an issue with one of the dependencies in grid-styled?

**Comment by jxnblk** [comment] 2017-06-20 23:27
Closing this until further context is provided

**Closed by jxnblk** 2017-06-20 23:27 UTC

**Comment by miguelbermudez** [comment] 2017-08-30 01:15
Sorry to reopen this, but I got the same error opening the site in IE11 as well. `Number.isInteger` is not supported in IE[[1](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger)]. 

From what I can gather, the library code isn't responsible. 
I think I've traced it to a dependency.

`Reline` is using `understyle @^1.2.0` [[2](https://github.com/jxnblk/reline/blob/master/package.json#L36)] which resolves to `understyle@1.3.0` which contains a function calling  `Number.isInteger`[[3](https://github.com/jxnblk/understyle/blob/v1.3.0/src/get-number-prop.js#L11)]

`Reline` hasn't bumped `understyle`, maybe it's a quick fix? 
Hope this helps, btw your tools are awesome!
Cheers!

**Comment by shawnmmatthews** [comment] 2018-01-04 21:54
Has anyone got a work around for this? I'm still not able to load jxnblk.com/grid-styled from IE11. I just want to make sure the bug is isolated to that page before testing it out in a project. Looks like an awesome library!
